import { createEnv } from "@t3-oss/env-nextjs";
import * as z from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.url(),
    AWS_REGION: z.string(),
    AWS_S3_BUCKET: z.string(),
    AWS_ACCESS_KEY_ID: z.string(),
    AWS_SECRET_ACCESS_KEY: z.string(),
    GOOGLE_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string(),
    BKASH_APP_KEY: z.string(),
    BKASH_APP_SECRET: z.string(),
    BKASH_USERNAME: z.string(),
    BKASH_PASSWORD: z.string(),
    BKASH_BASE_URL: z.url(),
    STEADFAST_API_KEY: z.string(),
    STEADFAST_SECRET_KEY: z.string(),
    STEADFAST_BASE_URL: z.url(),
    STEADFAST_WEBHOOK_AUTH_TOKEN: z.string(),
    SMS_API_KEY: z.string(),
    SMS_SENDER_ID: z.string(),
    SMS_BASE_URL: z.string(),
    META_ACCESS_TOKEN: z.string(),
    META_TEST_EVENT_CODE: z.string().optional(),
    FRAUD_CHECKER_API_KEY: z.string(),
    FRAUD_CHECKER_BASE_URL: z.url(),
  },
  client: {
    NEXT_PUBLIC_META_PIXEL_ID: z.string(),
    NEXT_PUBLIC_APP_URL: z.url(),
    NEXT_PUBLIC_API_URL: z.url(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AWS_REGION: process.env.AWS_REGION,
    AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    BKASH_APP_KEY: process.env.BKASH_APP_KEY,
    BKASH_APP_SECRET: process.env.BKASH_APP_SECRET,
    BKASH_USERNAME: process.env.BKASH_USERNAME,
    BKASH_PASSWORD: process.env.BKASH_PASSWORD,
    BKASH_BASE_URL: process.env.BKASH_BASE_URL,
    STEADFAST_API_KEY: process.env.STEADFAST_API_KEY,
    STEADFAST_SECRET_KEY: process.env.STEADFAST_SECRET_KEY,
    STEADFAST_BASE_URL: process.env.STEADFAST_BASE_URL,
    STEADFAST_WEBHOOK_AUTH_TOKEN: process.env.STEADFAST_WEBHOOK_AUTH_TOKEN,
    SMS_API_KEY: process.env.SMS_API_KEY,
    SMS_SENDER_ID: process.env.SMS_SENDER_ID,
    SMS_BASE_URL: process.env.SMS_BASE_URL,
    META_ACCESS_TOKEN: process.env.META_ACCESS_TOKEN,
    META_TEST_EVENT_CODE: process.env.META_TEST_EVENT_CODE,
    FRAUD_CHECKER_API_KEY: process.env.FRAUD_CHECKER_API_KEY,
    FRAUD_CHECKER_BASE_URL: process.env.FRAUD_CHECKER_BASE_URL,
    NEXT_PUBLIC_META_PIXEL_ID: process.env.NEXT_PUBLIC_META_PIXEL_ID,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  },
  skipValidation:
    !!process.env.SKIP_ENV_VALIDATION ||
    process.env.npm_lifecycle_event === "lint",
});
